### ISSUE TITLE
cant get pdf

### ISSUE THREAD

**Issue by kiga01** [Xportability/css-to-pdf#1]
hi guys, im trying to use this libarary but i cant get the pdf, im using the file u have here and this http://jsfiddle.net/kstubs/jrtM5/, im trying to get the pdf from a div, it have everything i want to print that i called 'recargar2', and then i try to execute the function from a button like this

$('#bt_pdf').bind('click', function (){
		printMe();	
	});

function printMe(render) {
    render = (render === undefined) ? false : render;
    xepOnline.Formatter.Format('print_me', {
        render: render,
        pageMargin: ".25in"
    });
}

but nothing happens just show me this my browser

TypeError: 'undefined' is not an object (evaluating '$(xepOnline.Formatter.__elm)[0].outerHTML')

and i put this on my document

<script src="../js/xepOnline.jqPlugin.001.js"></script>
because i have the js, on another folder.

**Comment by shanz17** [comment]
![image](https://user-images.githubusercontent.com/38685301/132996539-6fbd56c9-7b06-49d3-8254-ece3d5fbab5c.png)

Hi @kbrown01,
Recently I'm facing an issue I cant able to connect to the server.
we are facing this issue in production, Kindly assist

Thank you
