### ISSUE TITLE
Using css to pdf with an https connection 

### ISSUE THREAD

**Issue by mrrodriguesmanuel** [Xportability/css-to-pdf#10]
Hi everyone, 

I'm not able to use the xep service with an https connection on some browser. 
Try to change the xep url to https but it doesn't work (chandra service). 

Do you guys have any clue about that problem ? 

Thanks a lot !

**Comment by kstubs** [comment]
This is true of any secure domain trying to retrieve assets from an insecure domain, your browser will typically warn and block you.  The Chandra service you are hitting is intended as a test bed and low volume production solution.  We can offer you your own private and secure chandra service if needed.

Thank you for your interest!

Karl..

**Comment by kbrown01** [comment]
HTTPS site is in beta

**Comment by kbrown01** [comment]
You would change the calls to the service in the JS just changing them to https:

xep_chandra_service: 'https://xep.cloudformatter.com/Chandra.svc/genpackage',
xep_chandra_service_AS_PDF: 'https://xep.cloudformatter.com/Chandra.svc/genfile',	xep_chandra_service_page_images: 'https://xep.cloudformatter.com/Chandra.svc/genpageimages',

**Comment by mrrodriguesmanuel** [comment]
Perfect. Thank you. 

Nice work :)
