### ISSUE TITLE
Choose a Different Style Sheet

### ISSUE THREAD

**Issue by rherring** [Xportability/css-to-pdf#11]
Is it possible to choose a different style sheet to style the PDF?

I've tried using:
<pre>
return xepOnline.Formatter.Format('printPage',{render:'download', pageMediaResource: 'styles/print.css'});
</pre>
but it doesn't seem to be working. It's still using the CSS used on the screen.

**Comment by kstubs** [comment]
pageMediaResource property is not supported.  It was stubbed out early on when we were setting this up.  However, different style for PDF is fully supported; use @media print {} in your CSS.
CSS rules in here will override your standard CSS rules.  See our demo:  

http://cloudformatter.com/CSS2Pdf.Demos.PrintMedia

**Comment by rherring** [comment]
That doesn't seem to be working for me either. I even tried using the same "Print Media" stylesheet that is on the demo page. When I actually print the page, the stylesheet works fine, but when I save to PDF using the jquery plugin, it doesn't do anything that it's supposed to do.

If it helps, I'm using Firefox and the all the files live on my computer, I'm not hosting them anywhere yet.

**Comment by kbrown01** [comment]
Here's a fiddle, can you adopt to show us what is not working in your case? This one works, tested in Firefox and Chrome. http://jsfiddle.net/4k9dyrq3/6/

**Comment by rherring** [comment]
I created a super generic version of what I'm working on (since I'm under contract and am unable to display the actual work I'm creating) and posted it into the fiddle. After going back and forth with it, I've found out that when I include the styles directly into the HTML, it follows the styles of the <pre>@media print {}</pre>. If I were to link to the styles, then it bypasses the <pre>@media print {}</pre>.

Is this the expected result? Am I supposed to be putting all of my style into the HTML, or should linking to still work?

**Comment by kbrown01** [comment]
So I see your fiddle, but I am unclear what the issue is still. It does not matter if the styles are in the HTML or loaded via a link. I updated this simple Fiddle: http://jsfiddle.net/4k9dyrq3/9/

As you can see, the media-styles.css is loaded from an external stylesheet now and not internaal and yet it is the same. What should I be looking for in this example you sent that is not working?
