### ISSUE TITLE
Can't get "pdfproperties" to work

### ISSUE THREAD

**Issue by rherring** [Xportability/css-to-pdf#13]
I'm trying to setup the properties of the PDF that will be generated from my website, but no matter what information I input into this section, it doesn't show up in the generated PDF.

Specifically, the most important part I'm needing to get working, is the "UserPrivileges > Print Only" and "OwnerPassword". This is what I've placed just after the opening body tag `<body>` (is that the right place to put this)

    <body>
        <pdfproperties style="display:none;">
            <metainfo>
                <prop name="author" value="My Company Name"></prop>
                <prop name="title" value="My Document Title"></prop>
                <prop name="subject" value="My Document Subject"></prop>
                <prop name="creator" value="Adobe PDF"></prop>
                <prop name="keywords" value="CSS, PDF"></prop>
            </metainfo>
            <pdfpreferences>
                <pref name="pdf-version" value="1.7"></pref>
                <pref name="view-mode" value="auto"></pref>
                <pref name="initial-zoom" value="fit-width"></pref>
                <pref name="page-layout" value="continuous"></pref>
                <pref name="viewer-preferences" value="display-document-title"></pref>
                <pref name="crop-offset" value="0.5in"></pref>
                <pref name="crop-mark-width" value="0"></pref>
                <pref name="ownerpassword" value="Test1234"></pref>
                <pref name="userpriviledges" value="print"></pref>
            </pdfpreferences>
        </pdfproperties>
        
        
    </body>

Thanks

**Comment by kstubs** [comment]
We specifically read these properties from the container that is your print section, so include these properties there.  For example, if you have a div with ID = "print_me", inside this div include the pdfproperties tag.  
Thanks, and let us know if that works for you!

**Comment by kbrown01** [comment]
Assume issue is closed as the solution is given and no further comments made.
