### ISSUE TITLE
Question about css

### ISSUE THREAD

**Issue by reddo** [Xportability/css-to-pdf#17]
I've read through relevant parts of the documentation, but it's not mentioned anywhere: must the styles be inline in oder for the script to parse them? It doesn't seem to apply any of my styles to the rendered pdf. Maybe I'm doing something wrong.

Also a question bugging me: is it possible for the script to render a hidden element as the pdf? The layout of the pdf differs from my page and I'd like to hide a div on the page and the script render that.

**Comment by kbrown01** [comment]
Zoltan:

 

The Javascript is walking the “div” you pass and resolving all the styles, creating an alternate “div” with all the styles within it, inline.

Given that, it is unclear to me what styles are not resolving. CSS can be external file, inside <style> or right on the element and should all be resolved during the process.

If you can set up a fiddle with the issue using our template, that would be great: http://jsfiddle.net/zvx6eb7e/

 

I have seen others implement a hidden “div” and in fact, given the description above it is really the way the solution works. It should not be an issue.

See this sample: http://jsfiddle.net/zvx6eb7e/44/

 

It will print the “HiddenDiv”.

 

Kevin Brown

Xportability

**Comment by reddo** [comment]
Here's my fiddle: http://jsfiddle.net/zvx6eb7e/47/

Note that if I set the div on line 3 of the html to `display: none` I get an error from the server.

**Comment by kbrown01** [comment]
First, the issue with “hide” …

The problem here is that when a “div” is hidden, many things are not calculated or return values like height=”0”.

So the trick would be here to modify the code or set up your “hidden” div in a different way.

 

Best way … use visibility: hidden;  not display CSS

Other options I have seen is creating the “div” out of view (left:-1000px) ,,,

That gets you past this issue.

 

In a little bit, I will look into the rendering here as something is wrong and I am not sure what it is without inspecting the info sent to the server.

 

Kevin Brown

Xportability

**Comment by kbrown01** [comment]
As for formatting, it is close.

I did not go through all things but somethings appear like they are not there … but they are.

You use a lot of white text on colors but those rely on background color.

Setting the background color of the page exposes those things.

 

http://jsfiddle.net/zvx6eb7e/48/

 

Look at that sample.

 

Kevin Brown

Xportability

**Comment by reddo** [comment]
I know of this, I have gotten this far, but it still does not take consideration of all the css, especially background color and images. I'll do some more meddling with inline styles, maybe I find a solution that works.

Thanks for your help though.

**Comment by reddo** [comment]
Hi again,

I've updated my fiddle: http://jsfiddle.net/zvx6eb7e/49/

Ive included all of the images inline, with the full url, still it doesn';t render correctly. Maybe have a look and see if it can be fixed.
