### ISSUE TITLE
Breaking a div to more pages

### ISSUE THREAD

**Issue by reddo** [Xportability/css-to-pdf#18]
Is there a way to break a div to span multiple pages? Right now the plugin inserts  page-break before each div that wouldn't fit on a page which gives me a lot of empty space. I would be perfectly happy breaking those divs to span multiple pages just to fill the empty space.

![screen shot 2015-12-15 at 11 53 19](https://cloud.githubusercontent.com/assets/1180060/11807448/8414d6d4-a322-11e5-9d7d-9757c00f94f9.png)
![screen shot 2015-12-15 at 11 53 33](https://cloud.githubusercontent.com/assets/1180060/11807449/8416c228-a322-11e5-86d7-43d7154e6bc5.png)

Pay no mind to the missing images, I'm developing on a local site.

**Comment by reddo** [comment]
Also, Is there a way to remove the margins completely? I have set `pageMargin: 0` and I still get a pretty wide margin on the rendered PDF.

**Comment by kbrown01** [comment]
Zoltan:

 

It is unclear to me what you are saying.

Certainly you can format:

 

1)      One div which goes across multiple pages … http://www.cloudformatter.com/CSS2Pdf.CustomTipsTricks.HeaderFooter

This is many pages, but one div

2)      Many div’s each in its own page sequence (meaning each one will cause a new page but each div could be multiple pages) … http://www.cloudformatter.com/CSS2Pdf.Demos.MultiSelect

 

So I am confused by what you are saying unless you are attempting to use #2 style formatting by passing multiple div’s which would each go into their own page sequence (but this is not done by inserting page breaks).

 

“Right now the plugin inserts page-break before each div that wouldn't fit on a page which gives me a lot of empty space.”

 

I would say it does not BUT your CSS may in some way be specifying something like this. The “plug-in” doesn’t insert anything, it only scrapes the resolved CSS at the time of format for one (or more divs).

 

Can you create a fiddle showing your sample we can examine?

 

 

Kevin Brown

CEO, Xportability

(707) 869-8353 Direct

(925) 395-1772 Mobile

skype:kbrown01

 <mailto:kevin.brown@xportability.com> kevin.brown@xportability.com

**Comment by reddo** [comment]
Hi,

Here's a pdf that gets exported:
[CCA_Report.pdf](https://github.com/Xportability/css-to-pdf/files/63166/CCA_Report.pdf)
As you can see, there are a lot of weird page breaks.

It is generated from a single wrapper div, but after each pillar title there are 2 floated divs, one for the text and one for the eventual image on the right.

As you can see from the pdf each div which follows a title starting with pillar starts on it's own page, which is not what I would like.

Hope I'm making more sense.

**Comment by reddo** [comment]
I've set up a fiddle, as you requested: http://jsfiddle.net/zvx6eb7e/53/

**Comment by kbrown01** [comment]
That is solely on limitations of (print) formatting.

You cannot have two floating left/right styled div’s and hope for page breaks across them to be logical.

The issue does not “occur” in web-based formatting as there is no pagination.

It occurs in any pagination application – you can have multi-column pages, but you cannot have what is in essence two connected flows down the page on left/right layout.

 

Most easily said … bootstrap responsive grid design is accomplished with floats. A float cannot break across a page. If they are small enough, you can stack multiple together on a page left/right. 

 

What I believe you are experiencing is listed right here under “What can’t you do”:

 

http://www.cloudformatter.com/CSS2Pdf.NoCanDo.FloatInlineImages

 

This would be worse with spanning titles in between like yours but even the first one causes a page break.

 

What happens is that when you use floats (or things map to floats like in bootstrap’s responsive grid) in XSL FO, they are “out of flow” … meaning a page break cannot occur within them. So your columns of text are mapping to a block-container that has a height. If it can stack on the page with the previous content, you can get two or more on a page. But if the length is such that it cannot, the whole thing is moved to the next page. Formatting engines (that are not based on the visual view) do this. Of course you could just do as the browser and draw some line at page end and break things, but the browser also breaks down when that “line” would be within a few lines of the start/end of the div (not repecting widows/orphans) and even sometimes right through some image. Some browsers would bust the image in half. 

 

You could only implement a hidden “print” div that would use tables to mimic the left/right behavior you have or a customization to the conversion code on the backend which would handle the content differently than a generic mapping in trying to mimic HTML in Print. The other way would be to only float the images and not the content, but that would not give you left/right look that you have as the text would flow around the image.

 

Kevin Brown

CEO, Xportability

(707) 869-8353 Direct

(925) 395-1772 Mobile

skype:kbrown01

 <mailto:kevin.brown@xportability.com> kevin.brown@xportability.com

**Comment by reddo** [comment]
Would it be better if I'd use tables? 

Unfortunately that left-right look is required by the client, but I can go on and use tables, as this div is exclusively for the pdf and it's hidden to the viewer of the site.

The problem I had with using tables is that the text got squeezed to the left and the image took up most of the space, even when I set the td's width to 70%, respectively 30%. Setting the images width to a fixed value didn't help either.

**Comment by kbrown01** [comment]
Tables would work fine.
I would put each PILLAR in its own table.

You could even get creative and use continued styled headers if a page break occurs inside a “PILLAR” (see continued table headers sample).

If you need help setting up the page, we are always happy to assist.

 

I would at least do this:

 

One Pillar is one table

If you want continued headers … put TH = PILLAR title (continued) and use the special extension required for continued styled headers (drop the first table header)

Put the PILLAR title in the first row BUT keep that row with the next row so that the header is not orphaned on a page.

Have one table row with two cells

Cell on left is content, cell on right is one (or more images)

 

That will break the content in the cell and do what you wish.

 

Kevin
