### ISSUE TITLE
can't catch error coming from the server

### ISSUE THREAD

**Issue by NouranMahmoud** [Xportability/css-to-pdf#19]
Hi,
I was developing a pdf solution using your library... but I've encountered a very tough problem. sometimes I got an [error from your server ](http://s28.postimg.org/3kd2ykpml/Screen_Shot_2016_02_19_at_1_16_02_AM.png)  , this error redirects me to a new window of this URL `http://xep.cloudformatter.com/Chandra.svc/genfile` with **This webpage is not available** .

when I investigated the source code I found that you are implementing the request with originating HTML form and using the submit action without considering the **error** or **success** callbacks that the developers who use your library may need!.

Here is the code
```
jQuery('body').append('<form style="width:0px; height:0px; overflow:hidden" enctype=\'multipart/form-data\' id=\'temp_post\' method=\'POST\' action=\'' + xepOnline.Formatter.xep_chandra_service_AS_PDF + '\'></form>');		
jQuery('#temp_post').append('<input type=\'text\' name=\'mimetype\' value=\'' + options.mimeType + '\'/>');
jQuery('#temp_post').append('<textarea name=\'xml\'>' + xepOnline.Formatter.getFormTextData(printcopy) + '</textarea>');
jQuery('#temp_post').append('<input type=\'text\' name=\'filename\' value=\'' + options.filename + '\'/>');
jQuery('#temp_post').submit();
jQuery('#temp_post').remove();
```
I've tried to prevent the default `submit` and provide the submit with an **ajax** call to be able to get the **success** and **error** callbacks and handle them easily.

by this code
```
jQuery('#temp_post').submit(function(e){
e.preventDefault();
$(this).ajax({
data: $(this).serialize();
success: function (){};
error: function(){};
});
});
```
but didn't work because I didn't know which options ajax request will need to complete the request!

My question is: can I catch this error through `xepOnline.Formatter.formt` or any exposing? or how can I prevent this error from occurring?

**Comment by kbrown01** [comment]
You are free to improve the script ! That is why it is posted.

I assume you mean when posting for a download, there are alternatives to the download version that have error and success callbacks.

 

Kevin Brown

Xportability

**Comment by NouranMahmoud** [comment]
What is the alternative options? to be able to handle error and success callback?

**Comment by NouranMahmoud** [comment]
Thanks for your reply Kevin,

But I've tried to choose the `render: newwin` option as alternative. and it caused  this [error](http://s23.postimg.org/9nuncxoi3/Screen_Shot_2016_02_19_at_3_58_40_PM.png)  from the server to and also I am not able to catch any error callback from the library!.

This is the ajax request which causes the error
```
jQuery.ajax({
type: "POST",
url: current_mimetype == "image/png" || current_mimetype == "image/jpg" || current_mimetype == "image/gif" ? xepOnline.Formatter.xep_chandra_service_page_images : xepOnline.Formatter.xep_chandra_service,
processData: false,
contentType: false,
data: blob,
success: current_mimetype == "image/png" || current_mimetype == "image/jpg" || current_mimetype == "image/gif" ? xepOnline.Formatter.__processImages : xepOnline.Formatter.__postBackSuccess,
error: xepOnline.Formatter.__postBackFailure
});
```

It seems server side error or un-valid options are passed to the ajax request!

**Comment by NouranMahmoud** [comment]
Also when I tried to produce pdf through `render: newwin` .. the library internally converted the `newwin` to `download` again .. because of this [line of code](https://github.com/Xportability/css-to-pdf/blob/master/js/xepOnline.jqPlugin.js#L621)
```
options.render = (options.mimeType.substring(0,5) == 'image') ? options.render : 'download';
```

And I don't know if this is an issue in the library or you implemented the `newwin` only for `images`

**Comment by ven921** [comment]
Hello Nouran, 
     Did you find the solution for this issue??

**Comment by kbrown01** [comment]
I am a bit confused. You say you are producing PDF in your statement "Also when I tried to produce pdf .." but that line of code would not affect the options.render unless the mimetype is n image type. Are you producing PDF or are you producing Image?

**Comment by kbrown01** [comment]
No response so I am closing. The current server implementation only supports images in embed and newwin and not download mode. I have a working client side implementation for images that will provide download capabilities, once tested I will post. It will have typical client side limitations (blob is required because it is used along with local storage). 

We can implement server-side when we get some time to do so and some paying customers.
