### ISSUE TITLE
Unable to use iamges

### ISSUE THREAD

**Issue by santrupta3** [Xportability/css-to-pdf#22]
Hi
thanks for this nice and useful api. 

 I followed the steps to use this api. My web page came with the css but the images were not there. 
Please tell us is there any option to add the iamges to the pdf.

**Comment by santrupta3** [comment]
This only support cdn urls. it is not supporting local urls for the images.

**Comment by FishHooks** [comment]
In your options, try putting `embedLocalImages: true`. This should send any local images to the backend as a base64 encoded string so they can be rendered.

**Comment by kbrown01** [comment]
Sorry for late reply.
Your error is because your HTML is invalid. You have a div surrounding the whole html, head tags and such., The div to format must be inside the body tag. You cannot do this:

<div id="JSFiddle">

  <html lang="en">
