### ISSUE TITLE
Wondering Why Download Fails?

### ISSUE THREAD

**Issue by bvfeds** [Xportability/css-to-pdf#23]
My page fails to download, saying "http://xep.cloudformatter.com/Chandra.svc/genfile ERR_INVALID_RESPONSE". I've tried deleting various parts, and sometimes that will work, sometimes not. http://codepen.io/fsodergren/pen/pyagXj Can anyone explain what is happening, what I should change?

**Comment by FishHooks** [comment]
I got this same issue when using Chrome. When I did the same thing in Firefox, it worked. It seems to be an issue in the way Chrome handles the response from the back end.

**Comment by kbrown01** [comment]
Your error is because this file in invalid HTML and not structured for formatting. You must format a div inside the body and you have a div surrounding the html, head, body tags. This is not correct (even in HTML let alone formatting of that HTML):

<div id="JSFiddle">
  <html lang="en">
