### ISSUE TITLE
Is it possible to see this used > foStyle

### ISSUE THREAD

**Issue by cbrophy78** [Xportability/css-to-pdf#27]
I'd like to override my screen and print style sheet, but I didn't see this used as and example in your documentation.
From http://www.cloudformatter.com/CSS2Pdf.APIDoc.Usage
> foStyle - FO styles to place directly on the container element (to override cssStyles during XSL-FO rendering) as an array of objects whose key/value is the camel case CSS style name and a string value

```
some-style {
  width: 5in;
}
```
am I placing this on the container such as
`<td class="some-style" foStyle="overRideStyle: width:7in;">`
– or –
```
<button id="pdf" class="black-btn button-arrow-right no-print" onclick="return xepOnline.Formatter.Format('calc',{render:'download', filename:'Report', mimeType:'application/pdf', pageHeight:'8.5in', pageWidth:'11in', **foStyle:'some-style{width:7in;}'**, pageMediaResource:'library/css/print.css'});">
   CREATE PDF
</button>
```

**Comment by cbrophy78** [comment]
i can get this to work
```
<td foStyle="color: #0F0;">
  some text
</td>

```

but not 
```
<td foStyle="width: 9in;">
  some text
</td>

```

**Comment by kbrown01** [comment]
The first works because color is a valid XSL FO attribute. The second does not work because you cannot override the width of a single table cell (as that would make no sense as all table cells in a particular column are of the same width).

**Comment by cbrophy78** [comment]
ok.
