### ISSUE TITLE
Another @media print problem

### ISSUE THREAD

**Issue by Lolanger** [Xportability/css-to-pdf#29]
Hey,
so far i really like your project :)
But within the final stage of implementing css2pdf I am unable to figure out how to style my generated pdf.
I have a table, which I dynamically fill with rows and columns. IDs are assigned with JS, referring to a css file.

`<table id="classTable"></table>`

I use @media print to change the table properties (black text color, white background ...). When I call window.print() I get a nice version of the table to save as pdf.
But when I use css2pdf the @media print stylings are ignored!

`return xepOnline.Formatter.Format('classTable',{render:'download',pageWidth:'279mm', pageHeight:'216mm'});`

Thanks in advance for your help,
Lolanger

**Comment by kbrown01** [comment]
It is hard to diagnose without a simple example, can you set up a fiddle for us in our template?

 

I <http://jsfiddle.net/zvx6eb7e/>  did this, hit the PDF button and you see green cells not red cells.

 

http://jsfiddle.net/zvx6eb7e/186/

 

Kevin Brown

Xportability

**Comment by Lolanger** [comment]
Hey,
thanks for the fast answer.
I´m not sure if a fiddle is really useful. I will try to explain without fiddle if its not clear then I will create one. I basically have a table within my HTML file

`<table id="classTable"></table>`

I fill it with a lot of this:

```
var tr = document.createElement('TR');
var td = document.createElement('TD');
	td.innerHTML = "1. Somi";
	td.setAttribute("class", "classTableTDNote")
	tr.appendChild(td);
```

I have two different versions of the classTableTDNote

style.css

```
#classTable{
  margin:10px;
  color:#D6D6D6;
  text-align:center;
  font-size: 14px;
  font-size: 1rem;
  border-collapse: collapse;
}

.classTableTDNote{
  width:40px;
}
```

stylePrint.css

```
@media print{
#classTable{
  margin:10px;
   color:#000000;
  text-align:center;
  font-size: 10px;
  font-size: 0.8rem;
  border-collapse: collapse;
}
}
```

Then i call a funtcion which returns 

`return xepOnline.Formatter.Format('classTable',{render:'download',pageWidth:'279mm', pageHeight:'216mm'});`

But the textcolor is still  `color:#D6D6D6;` and not   color:#000000;

**Comment by kbrown01** [comment]
Well the way that @cloudformatter works is that it creates a copy of the target to print, applies all @media rules, then scrapes the HTML and sends to a server to be formatted.

 

One thing to test for me … can you just surround the table itself with a <div> with an id (like id=’tablediv’) and then send that <div> to print and not only the table.

There could be an issue that the software expects a div that is the print container and the @media rules may not be applied to the overall print container.

 

If this does not work, then the only way I can debug is to walk the code and see why stylePrint.css is not being applied so I would need a fiddle to do this or a link to the site if it is open.

 

Kevin Brown

Xportability

**Comment by Lolanger** [comment]
Hey,
I just created a fiddle and it works without problems. If I try the exact same code offline its not working...

**Comment by Lolanger** [comment]
"Offline" seems to  be the problem. I probably missed some server-side functionality?

**Comment by kbrown01** [comment]
What do you mean by “offline”. Do you mean on localhost?
