### ISSUE TITLE
Website off the air

### ISSUE THREAD

**Issue by leofontes** [Xportability/css-to-pdf#30]
Hey,

I really like how easy to use your plugin is, however your website seems to be offline.

After clicking on the script to generate the pdf, it redirects to this website:
http://xep.cloudformatter.com/Chandra.svc/genfile

That is offline, from Chrome: 
This site can’t be reached

xep.cloudformatter.com took too long to respond.
Go to http://cloudformatter.com/
Search Google for xep cloudformatter Chandra svc genfile
ERR_CONNECTION_TIMED_OUT

**Comment by cbrophy78** [comment]
I saw that a few times when I was putting something together, usually its something wrong with your code. like its trying to go through the code and it is missing a "" or ;

**Comment by leofontes** [comment]
http://cloudformatter.com/ is offline, try accessing it from your browser. I copied the code from the README, unless they have it wrong there, it's not wrong on my end.

Are you able to use this plugin right now?

**Comment by kbrown01** [comment]
Where are you located? Recently @cloudformatter was hit by formatting requests for the Government of Mexico, approximately 10,000 or more per day. After numerous requests through their website we could reach no one. We analyzed the logs and blocked the majority of IP addresses coming from those areas. If you send me offline via email (kevin.brown@xportability.com) your IP I can see if yours was blocked and open it back up.

**Comment by kbrown01** [comment]
That would be the reason most likely as @cloudformatter has not been down for anything recently and if you cannot even reach the website, then your address is likely blocked,

**Comment by leofontes** [comment]
Yes, I'm located in Brazil, I guess you blocked all Latin America 😢 

Any chance you can unblock Brazil? I'll send you my IP.

**Comment by kbrown01** [comment]
Try again.

 

Kevin Brown

Xportability

**Comment by leofontes** [comment]
Yes! Thank you very much!

**Comment by kbrown01** [comment]
No problem. I released all the IP blocks for now by disabling the rule. I have your recorded if I need to reinstate something and will be sure to exclude you. Sorry for the inconvenience but it is occasionally required when the actions of some ruin things for the many. There are commercial solutions for those people that need the volume, security and guaranteed uptime.

**Comment by leofontes** [comment]
Absolutely! Thank you again

**Comment by DougMcKay** [comment]
Hi Kevin, 

I'm seeing this same issue now with all of our requests failing.  Did you re-enable the blocking rule?
