### ISSUE TITLE
Availability on npm

### ISSUE THREAD

**Issue by JosefWN** [Xportability/css-to-pdf#31]
Will css2pdf be available on npm?

**Comment by JoshuaCWebDeveloper** [comment]
Once PR #54 has been merged, users will be able to install via  npm as `Xportability/css-to-pdf`. However, the remaining steps to publishing on npm should be taken by following https://docs.npmjs.com/getting-started/publishing-npm-packages. 

For the time being, users should be able to use my fork to install via npm as `JoshuaCWebDeveloper/css-to-pdf`.
