### ISSUE TITLE
PDF issues

### ISSUE THREAD

**Issue by prashant-sehta** [Xportability/css-to-pdf#33]
1. The generated pdf is having issue, so when I try to print the PDF, then I get the following error, but file gets printed.

![1](https://cloud.githubusercontent.com/assets/17457017/16906679/692ef172-4cd9-11e6-93b7-f5ce4e80dfab.png)

2. The generated pdf is having issue, so when I try to close the PDF, then every time it ask me to save the changes (even though I have not changed anything in file):

![2](https://cloud.githubusercontent.com/assets/17457017/16906685/7ec10a7a-4cd9-11e6-9436-5c76915a13f2.png)

Can you please help to resolve these issues?

**Comment by kbrown01** [comment]
You have two issues here, the first is not clear and would require the actual PDF to diagnose. The second I have tracked down and fixed. The error was internal to the web service that started with the implementation of insertion of PDFs. This should be fixed as it is fixed on the main web site now.

**Comment by prashant-sehta** [comment]
Hi Kevin,

The second issues seems to be fixed. However, when I open the pdf in Adobe Reader, it gives the following error in first three pages but 4th page looks good:

![3](https://cloud.githubusercontent.com/assets/17457017/16941312/f400d2ec-4dac-11e6-90a7-6cc8e2a7b283.png)

But the same pdf can be viewed in chrome browser. I'm attaching the pdf for your reference. Please have a look and let me know where is the problem:

[TestGraphReport.pdf](https://github.com/Xportability/css-to-pdf/files/370823/TestGraphReport.pdf)

I've also setup a sample fiddle. Please check and let me know if I'm worng somewhere or missing something.

https://jsfiddle.net/t1gocqkj/2/

**Comment by kbrown01** [comment]
I will look into this over the weekend, booked up on other things currently.

**Comment by kbrown01** [comment]
Please try again, I changed some software on the server ... http://jsfiddle.net/t1gocqkj/4/ seems to work

**Comment by prashant-sehta** [comment]
Thanks Kevin. Its working perfectly now.
