### ISSUE TITLE
css2pdf can't  Convert chinese utf8 html to pdf

### ISSUE THREAD

**Issue by AndyXGWang** [Xportability/css-to-pdf#35]
Hi 

I have a question is when i convert a Chinese website html to pdf and pdf can generate successful but the content with Chinese was blank..

Could you kindly help on that?
Website Url: http://www.wangfz.com/archives/2957 (in chinese)
Div class = content
Thanks
Andy

**Comment by AndyXGWang** [comment]
issue fixed since font-family: FangSong.... Don't why support this font only?

**Comment by kbrown01** [comment]
The server engine has many fonts but not every font in the world. They need to be installed on the server where the content is formatted to PDF. If you have particular needs for certain fonts, you can ask us and we can see if we have access to use it.

**Comment by AndyXGWang** [comment]
Hi  Kbrown  

thanks for your kindly feedback, currently we are using "Segoe UI" font as default.
Could you kindly try to install this font on your server?  :+1: 

and following as option.
"Lucida Grande",
Helvetica,Arial,
"Microsoft YaHei",
FreeSans,Arimo,
"Droid Sans",
"wenquanyi micro hei",
"Hiragino Sans GB",
"Hiragino Sans GB W3"
,FontAwesome,sans-serif

Best Regards
Andy

**Comment by kbrown01** [comment]
I have added Segoe UI – Normal, Bold, Italic and Bold-Italic

 

Sample attached.

 

Kevin
