### ISSUE TITLE
Getting "This site can’t be reached Temporarily down or moved" with 4 SVG in one request

### ISSUE THREAD

**Issue by bruceiow** [Xportability/css-to-pdf#36]
When calling the xepOnline.Formatter.Format method with 4 SVG's and a h2 heading for each of them, I am seeing the request bomb my page to "This site can’t be reached Temporarily down or moved". Is there a request size limit? I am trying to get 4 Morris charts on to the one PDF. 

I have several other places where I call that method, each passing one SVG and they complete fine.

**Comment by kbrown01** [comment]
To answer your question: Is there a request size limit?

The answer is yes, however that may not be the error.

1)      Can you fix the text in your question … “When calling the xepOnline.Formatter.Format method with 4 SVG's and a __________ for each of them …” What is the ____________ ?

2)      You can either create a fiddle or follow the instructions here: http://www.cloudformatter.com/CSS2Pdf.APIDoc.DebuggingHints and send us the info to support@xportability.com <mailto:support@xportability.com>  and we can evaluate and see if you are hitting the request size limit or if there is a different issue.

 

Kevin Brown

Xportability

**Comment by kbrown01** [comment]
One note on the web page for debugging ... the code has changed since that was written so those stop points may be at different line numbers.

**Comment by bruceiow** [comment]
Sorry I put in an HTML tag in my comment - sorted now.

**Comment by kbrown01** [comment]
Got it, I thought it was a tag but needed to be clear. So to diagnose we need either of those two methods above. It could be max size issue that we can evaluate and change if possible or it could be something else in the SVG. Do each of the SVGs format separately?

**Comment by kbrown01** [comment]
Closing as no response.
