### ISSUE TITLE
is there a way to set generated PNG size equal to div size?

### ISSUE THREAD

**Issue by JustPepper** [Xportability/css-to-pdf#39]
im trying to start a project that generates an image from html div, something like a template, i want to know if i can set the generated PNG o PDF equal to div width and height.

**Comment by kbrown01** [comment]
It is not clear what you mean but if you look at this sample page:

 

http://www.cloudformatter.com/CSS2Pdf.Demos.Structures

 

Select Embed -> As PDF or Embed as PNG @120dpi the embedded result is the same size as the div (in in fact replaces the div).

You would use 120dpi for image result if you want it to be the same size.

 

Kevin Brown

Xportability

**Comment by kbrown01** [comment]
Or … are you looking for something that yields the *exact* size meaning not page-oriented but width and height?

That is not implemented but could be done for HTML content, it does work currently for SVG only –

 

See http://www.cloudformatter.com/CSS2Pdf.SVGCharts.HighCharts#

 

Select Embed-> PDF or PNG on that chart and the chart is replaced by the result which is only formatting the SVG.
Is this what you are interested in only with HTML content?

 

To do this, you would need to get the height of the div and set that in the sending of the request as the pageHeight (and also account for or remove margins).

 

Kevin Brown

Xportability

**Comment by kbrown01** [comment]
No answer, closing
