### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by gruberb** [Xportability/css-to-pdf#4]
I got redirected to "http://xep.cloudformatter.com/Chandra.svc/genfile" and a error page in chrome after executing the example code. 

Any success with this library lately?

**Comment by kbrown01** [comment]
Bastian:

 

It should be up and running. 

I just tried this page to format: http://www.cloudformatter.com/CSS2Pdf.APIDoc.Usage

Worked fine, it calls that service.

Possibly it was a temporary network/machine issue? That server is hosted on Amazon Web Services.

Just hitting this:

http://xep.cloudformatter.com/Chandra.svc?wsdl

returns the WSDL for me also.

 

Kevin Brown

Cloudformatter

**Comment by k-yang** [comment]
I am also getting this issue. I made several requests today and all of a sudden I started getting this error.

**Comment by kbrown01** [comment]
We did a few modifications on the servers today, taking them up and down.

Are things ok now?

 

If not you can always email us at support@xportabillity.com <mailto:support@xportabillity.com> 

 

Kevin

**Comment by k-yang** [comment]
Things still aren't working for me.

I also tried e-mailing you guys at that e-mail address and this is what I got:

Delivery to the following recipient failed permanently:

     support@xportabillity.com

Technical details of permanent failure:
DNS Error: Address resolution of xportabillity.com. failed: Domain name not found

----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:date:message-id:subject:from:to:content-type;
        bh=Qh8OtxZFCb4fHjTNh0lSI3oIDXHzAA55WqiJuq9mcsY=;
        b=UzhQvz83/mJp0zbRjupIcYHtPNyHaz1Ep2uAC3RxkjZBT1/bTqmtiq6Y/Qq7j9Egoi
         iNe2KSlw7aK3l0BR5k2ndzT/SN/hy+qC7Yp8IofI3zmfJFaLLAYI9sWAyek4tBeqjPWy
         dvGCCZALegvV+EgNd81qlwvoSKGnAJ85XetS5l4GLalOqIM4uQwg9Dw/juQdBpcWUCvW
         r+yL4GnV0iK+23jqm/k9Tnsv1oBNsl4pppKtbeoVqyKI85D+N//LCeuXrjze4zWmr1Lx
         7b/go5ZdLQrjuc6ie1LmE8HNupA7KMvC+TwViTe6+kffxAzIx4gY3yGL7byTiLpw8R/g
         5F6w==
MIME-Version: 1.0

**Comment by kbrown01** [comment]
Kevin:

 

Does it work if you run from the web site?

 

Like visit http://www.cloudformatter.com/CSS2Pdf.Demos.Structures and use the “Out PDF” button?

 

Both that works for me and I can send email to support@xportability.com <mailto:support@xportability.com>  from outside that domain even so I am not sure what the issue is.

 

Kevin

**Comment by kbrown01** [comment]
The email is support@xportability.com <mailto:support@xportability.com> 

 

One “l” not two.

 

That is one problem down.

 

Kevin

**Comment by DhavalGPatel** [comment]
Even I redirected to "http://xep.cloudformatter.com/Chandra.svc/genfile" error page by executing the code.

do we need to embed other things..?

**Comment by joelwass** [comment]
can the server side code be made public? the meat behind the xep.cloudformatter.com ? so that we don't get error pages 50% of the time?

**Comment by prashant-sehta** [comment]
I'm being redirected to http://xep.cloudformatter.com/Chandra.svc/genfile when I try to download the pdf file using xepOnline service from my local. Is the service down again?

**Comment by kbrown01** [comment]
Doesn’t seem to be, but I just tested now.

You can always just format one of the simple pages on the site at: http://www.cloudformatter.com/CSS2Pdf.Demos.Structures

If that works, then it is up and something is wrong in the data being sent, if that is down then a direct email to us at feedback@cloudformatter.com <mailto:feedback@cloudformatter.com>  gets to us.

 

Kevin  Brown

Xportability

**Comment by prashant-sehta** [comment]
Thanks Kevin,

As you said, the issue was in the data and I've fixed that. It is working fine now.
Thanks for your help.

**Comment by lexigren** [comment]
Looks like service is down right now. Is it for long?

**Comment by ktssshree** [comment]
The site can't be reached sometimes,when am trying to export the content to pdf the http://xep.cloudformatter.com/Chandra.svc/genfile might be temporarily down or it may have moved permanently here is screen shot 

Note:Am having a working internet connection

![capture](https://user-images.githubusercontent.com/34056410/33367307-1447c656-d514-11e7-836e-54aa1b7e928e.PNG)

**Comment by ktssshree** [comment]
Is there any one found the solution for the above mentioned problem ????

**Comment by nishanthan89** [comment]
any one found the solution?

**Comment by shanz17** [comment]
![image](https://user-images.githubusercontent.com/38685301/127812548-f84580b8-a70e-4bb4-a57c-8b7643a125b3.png)

The webpage at https://xep.cloudformatter.com/Chandra.svc/genfile might be temporarily down or it may have moved permanently to a new web address.

Has anyone found the solution?? Please Update, thank you @kbrown01

**Comment by kbrown01** [comment]
We will take a look. This sometimes happens when Windows Updates has downloaded a bunch of updates and we have not applied them. There is a huge Windows update happening now. We'll patch to the latest and have it back in a few hours.

**Comment by shanz17** [comment]
![image](https://user-images.githubusercontent.com/38685301/132809683-bc409304-e255-42ca-b96c-5289329cb662.png)
Hi All, Currently facing the issue. Is this site is down

**Comment by kbrown01** [comment]
It is back up, we were patching the system.

 

Kevin Brown

Owner and CEO, Xportability LLC
 ***@***.***> ***@***.***
skype: kbrown01
+1 (925) 395-1772

**Comment by bedrettin** [comment]
**TR/tr çözüm**

http://xep.cloudformatter.com/Chandra.svc/genfile 

bu hatayı alan arkadaşlar. sorun çözüldü..
öncelikle sorunu anlatayım.
web sitenize kurulumu yaptığınızda ssl sertifika olmadan çalışıyor. fakat ssl sertifika olan sitenizde bu hatayı alırsınız.
yani bu linkler http:// şeklinde doğru adresi bulamıyor.
xepOnline.jqPlugin.js dosyanızı açın.
yaklaşık 580. satırlarda şu linklerin http:// olan kısımlarını "s" ekleyerek kaydedin. yani https:// şeklinde olmalı.

xep_chandra_service: '**https**://xep.cloudformatter.com/Chandra.svc/genpackage',
xep_chandra_service_AS_PDF: '**https**://xep.cloudformatter.com/Chandra.svc/genfile',
xep_chandra_service_page_images: '**https**://xep.cloudformatter.com/Chandra.svc/genpageimages',
entity_declaration:'<!DOCTYPE div [  <!ENTITY % winansi SYSTEM "**https**://xep.cloudformatter.com/doc/XSL/winansi.xml">  %winansi;]>',
xsl_stylesheet_declaration: '<?xml-stylesheet type="text/xsl" href="**https**://xep.cloudformatter.com/doc/XSL/xeponline-fo-translate-2.xsl"?>',
svg_xsl_stylesheet_declaration: '<?xml-stylesheet type="text/xsl" href="**https**://xep.cloudformatter.com/doc/XSL/xeponline-svg-translate.xsl"?>',

Başarılar dilerim.

**EN/en Solution**

Guys who got this error. problem solved.
Let me first explain the problem.

When you install it on your website, it works without an ssl certificate. but you will get this error on your site with ssl certificate.
so these links cannot find the correct address in the form of http://.

Open your xepOnline.jqPlugin.js file.
Save the http:// parts of these links by adding "s" on lines 580. so it should be in the form of https://.

xep_chandra_service: '**https**://xep.cloudformatter.com/Chandra.svc/genpackage',
xep_chandra_service_AS_PDF: '**https**://xep.cloudformatter.com/Chandra.svc/genfile',
xep_chandra_service_page_images: '**https**://xep.cloudformatter.com/Chandra.svc/genpageimages',
entity_declaration:'<!DOCTYPE div [  <!ENTITY % winansi SYSTEM "**https**://xep.cloudformatter.com/doc/XSL/winansi.xml">  %winansi;]>',
xsl_stylesheet_declaration: '<?xml-stylesheet type="text/xsl" href="**https**://xep.cloudformatter.com/doc/XSL/xeponline-fo-translate-2.xsl"?>',
svg_xsl_stylesheet_declaration: '<?xml-stylesheet type="text/xsl" href="**https**://xep.cloudformatter.com/doc/XSL/xeponline-svg-translate.xsl"?>',

Good luck.

**Comment by kbrown01** [comment]
Tested just now. Works fine. You may have tested when we had it down for updates? Who knows? Free is free.
