### ISSUE TITLE
FormatGroup

### ISSUE THREAD

**Issue by mthor** [Xportability/css-to-pdf#41]
I have the pdf working how we want it!!  Only one issue is I need to have different footers on each page,  I see there is a FormatGroup but I cannot find an example. I have tried <FormatGroup> and some other things, but I have had no luck. can you guys point me in the right direction?

**Comment by kbrown01** [comment]
http://www.cloudformatter.com/CSS2Pdf.Demos.MultiSelect

Look at the source behind that page. You put header/footer elements inside each div and pass the list of div's to format.

**Comment by mthor** [comment]
ah, very simple!!  thanks!
