### ISSUE TITLE
css boostrap not loaded while export to pdf

### ISSUE THREAD

**Issue by Zeltron** [Xportability/css-to-pdf#45]
Are this method can be used to import/load css boostrap ?

` onclick="return xepOnline.Formatter.Format('printme',{render:'download'},{pageMediaResource:'../styles/vendor/bootstrap.min.css'},{pageMediaResource:'../scripts/vendor/bootstrap/bootstrap.js'});"`

**Comment by kbrown01** [comment]
I do not understand the question. Certainly bootstrap CSS (except some of the print media rules) if loaded on your page would be available in the print out. The whole @cloudformatter website uses bootstrap.

**Comment by Zeltron** [comment]
Sorry if you don't understand what i'm asking ... i'm trying to using this library with angular, by using ng-click . but when i export to PDF the CSS is mess up likes it not taking the CSS bootstrap . In the system it arrange properly using the CSS bootstrap 

This how i'm calling the xepOnline in controller :

`  $scope.exportResume = function(){
              console.log("export");
              return xepOnline.Formatter.Format('printme', {render:'download'});
          };
`

**Comment by kbrown01** [comment]
You have to set up a fiddle to understand. When that Javascript is run, it walks the div (or div's) in question and copies the exact content and resolved css to another div.  To me, it sounds as if your page is not loaded or the result of the "click" is not finished.

**Comment by Zeltron** [comment]
kbrown01 , the issue is solved . It is because of the structure of my html is not well organized. Thank you .

By the way i'm have some doubt regarding this library:

1. Are this library dependency with these three services ? if the services is down then we unable to export/print right ?

xep_chandra_service: 'https://xep.cloudformatter.com/Chandra.svc/genpackage'
xep_chandra_service_AS_PDF: 'https://xep.cloudformatter.com/Chandra.svc/genfile'
xep_chandra_service_page_images: 'https://xep.cloudformatter.com/Chandra.svc/genpageimages'

2. Are this library need  internet connections ? if no internet connections it won't work ?

**Comment by kbrown01** [comment]
It depends on any one of the three -- they are used for different ways of formatting.
Of course the solution depends on them as it is a remote formatting service.
You cannot download the remote service, it is not free -- only free to use.
