### ISSUE TITLE
Background-color not transferring to PDF

### ISSUE THREAD

**Issue by melneff** [Xportability/css-to-pdf#47]
I have an div that I'm transferring to pdf but I cannot get the background-color to transfer in a th. Other things transfer fine, but if I set the background-color or color of the th it will not show up on the pdf. 

thead style="background-color:red;"

do I have to set something else first to get this to transfer?

**Comment by kbrown01** [comment]
what is thead? I do not quite understand your example. Do you mean "th style=.."

**Comment by kbrown01** [comment]
Like this: http://jsfiddle.net/zvx6eb7e/266/

**Comment by kbrown01** [comment]
Or this if you are trying to do the whole header ... http://jsfiddle.net/zvx6eb7e/269/

**Comment by kbrown01** [comment]
Or this works too using thead element ... http://jsfiddle.net/zvx6eb7e/271/

**Comment by melneff** [comment]
Hello, I found my issue from looking at the jsfiddles.

thanks!

**Comment by kbrown01** [comment]
Perfect! Closing.
