### ISSUE TITLE
Problem using pageMediaResource

### ISSUE THREAD

**Issue by jonnydevv** [Xportability/css-to-pdf#5]
Hello,

I'm having problems using the pageMediaResource option.

I can print the div but the css seems to having no effect.

onclick="return xepOnline.Formatter.Format('print-article0',{pageMediaResource:http://test.dev/assets/css/article.min.css});"

Thanks in advance

**Comment by kstubs** [comment]
Joao,

There could be many things going on here.  Depending on how complex your
HTML is, and several other factors, its hard to help without asking of you
to strip this down to a basic example to see if that works.  Have you tried
this approach?  If so, can you provide simple HTML sample or jsFiddle?
Karl..
