### ISSUE TITLE
table caption tag not converted

### ISSUE THREAD

**Issue by gjohncock** [Xportability/css-to-pdf#51]
would be great if contents of the table "caption" tag could be converted

**Comment by kbrown01** [comment]
Thanks! That should not be that difficult as the rendering engine used is XSL FO and supports table caption. We will look into supporting it in the next few day and update you here.

**Comment by kbrown01** [comment]
See http://www.cloudformatter.com/CSS2Pdf.Demos.Tables extended example. I have added support for table "caption" tag.
