### ISSUE TITLE
filename option doesn't work

### ISSUE THREAD

**Issue by solleOlle** [Xportability/css-to-pdf#52]
I use the filename option. It doesn't matter what value I set, I always get 'document.pdf' file

**Comment by kbrown01** [comment]
Please check again. I found a bug in the latest update (blacklist implementation) that broke this functionality. I have fixed and updated the site.

**Comment by kbrown01** [comment]
Note: This change was in the backend server and not the Javascript. There is no update to the JS.

**Comment by kbrown01** [comment]
I am closing this. The bug was found in the backend and have tested and it is fixed.
