### ISSUE TITLE
page-break rules not respected

### ISSUE THREAD

**Issue by adaptifyDesigns** [Xportability/css-to-pdf#57]
First of all, thanks for this script. It's definitely the easiest client-side pdf generator I've found. 

I've been having trouble getting the pdf to respect my page-break rules. 

For example, I have sections of content that are structured like the following:

```html
<div>
    <h2 style="page-break-after: avoid;">Section Title</h2>
    <div style="page-break-before: avoid;">
        All the section content goes here. Mostly paragraph text, etc.
    </div>
</div>
```

The goal with this is to avoid page breaks directly after a section title because it's unsightly and jarring for the reader.

But even when doubling up on the page break rules, my pdfs are still breaking directly after section titles.

At first I just had the page break rules in my stylesheet. Then I moved them into the "@media print {...}" section of my stylesheet. And when that still didn't work, I finally wrote them inline directly on the elements, as seen above, but it still isn't working.

In the js console output, when I search for inline "page-break-..." occurances there are no such inline css rules applied to any of the elements. 

Are the rules getting ignored or stripped for some reason?

Any suggestions?

Thank you in advance for your time and any assistance you can provide.

Cheers!

- Colin

**Comment by kbrown01** [comment]
See http://www.cloudformatter.com/CSS2Pdf.CustomTipsTricks.XSLFOStyling

 

It shows all examples of keeps and specifically how to set headings to keep with the following information.

 

 

Kevin Brown

skype:kbrown01

 <mailto:kevin.brown@xportability.com> kevin.brown@xportability.com

**Comment by adaptifyDesigns** [comment]
Got it! Awesome.

Thank you very much :-)
