### ISSUE TITLE
Service down!!?

### ISSUE THREAD

**Issue by dabrovski-pl** [Xportability/css-to-pdf#65]
**After trying to render a pdf file, after a longer while I'm redirected to:**
http://xep.cloudformatter.com/Chandra.svc/genfile

**And get:**
"can’t find the file at http://xep.cloudformatter.com/Chandra.svc/genfile."

PS.
I've been using the service for some time and everything's been working until today :(.

**Comment by kbrown01** [comment]
The service is free. Free means free in many ways, like we are free to take it down for a bit to update it. There are occasions when this happens. There are occasions when some user floods the service with 1000s of downloads a minute and also causes issues for others. we try to minimize all this as best we can.
