### ISSUE TITLE
Conditions of service

### ISSUE THREAD

**Issue by jdat82** [Xportability/css-to-pdf#7]
Hi, is it a paid service ? css-to-pdf uses a server to generate pdf but there is no information related to conditions of service... Thanks.

**Comment by kbrown01** [comment]
Its free to use. But certainly not abuse. It is our primary development site and we may take it down or cause an issue in development updates although we certainly do not try to do it as we also have several staging sites we use for testing. 

 

“Abuse” above means if we find the site is overloaded from a particular address for 1000s of requests, we may throttle/exclude that connection as we do actually pay money for it (it multiple hosted AWS servers which cost us $s). We do not record anything on our side about the documents (they are in fact all processed in memory and never on disk), we only store IPs and counts of pages/documents.

 

We also have folks that wish their own private space and we do that too. It’s a monthly/semi-annual/annual fee based on volume in which we create the AWS site for you, maintain it completely for you and you are the only person on it so you can be up 99.99+% with a guarantee of no interruptions. You give us the address and its yours to have and use (like … myformatter.mycompany.com). We do all the setup, support, mapping to your address and security even to lock it down to you. We also keep you updated with latest and greatest tested JS when you wish as we enhance it. We have just released a dozen or so new features like PDF bookmarks, PDF attributes and security and many more in process.

 

So there is no “terms” of service and no guarantee to use it for free. You can, play nice, don’t abuse it. There are 100s of sites hitting it today for formatting.  If you would like a more commercial set of terms, we do that too and have many customers with their own sites. Just contact us through the other site we are building for the business: http://beta.xportability.com/Contact

 

Kevin Brown

Xportability

**Comment by jdat82** [comment]
Thank you. Maybe you should set a page somewhere or a wiki page in the repo to explain that. Regards.
