### ISSUE TITLE
Hi there, is http://xep.cloudformatter.com down?

### ISSUE THREAD

**Issue by tonyshiG-zz** [Xportability/css-to-pdf#72]
Hi There,

I really like how easy to use your plugin is, however your website seems to be offline.

After clicking on the script to generate the pdf, 

This site can’t be reached

xep.cloudformatter.com took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

**Comment by kbrown01** [comment]
It was down for maintenance window.
