### ISSUE TITLE
Uncaught TypeError: Cannot read property 'document' of null

### ISSUE THREAD

**Issue by litehacker** [Xportability/css-to-pdf#75]
the error appears in the second row here:
here is the link of the example:
http://3d-baski.com/pay-callback.php?first_name=Giorgi&last_name=Gvimradze&address=Karadeniz%20Teknik%20%C3%9Cniversitesi&state=Trabzon&city=Trabzon%20Merkez&zip_code=61080&phone_number=5075442183&email_address=natceo@gmail.com&price=26.25

```
var win = window.open("","_blank","titlebar=yes");
			     win.document.title = "XEPOnline Result";
			     win.document.write('<html><head>');
			     win.document.write('</head><body height="100%"><div id="target" style="height:100%;overflow-y:auto">');
```

**Comment by kbrown01** [comment]
Got around to checking this, it appears that is not using our code. Closing.
