### ISSUE TITLE
Safari mobile problem

### ISSUE THREAD

**Issue by fabrikatur** [Xportability/css-to-pdf#8]
Hi.
Congrats on an excellent piece of software. It does exactly what I want on Firefox, Safari Mac, Chrome (mac and smartphone) and smbdy has tested IE. But I can't get the PDF to save/open up on my iPad (iOS 8.3), eg. in iBooks. Do you know if there is a general issue with iOS? Or might I be doing smth wrong?
Thanks & cheers.

Update: Sorry for bothering. Have figured it out myself. Using enabled 'restrictions' in iOS settings leaves you with a grey screen when opening the pdf in Safarin mobile without a hint that this is the problem.

**Comment by kbrown01** [comment]
Thanks very much!

That isn’t a platform we have on hand to test. 

I will look around and see if I can find someone with that combination.

 

Kevin Brown

Xportability

**Comment by kbrown01** [comment]
You may wish to check the latest where we support both images and SVG returned from the system. These should be supported in any browser
