### ISSUE TITLE
Not exporting all elements

### ISSUE THREAD

**Issue by rpm192** [Xportability/css-to-pdf#80]
Hello,

First of all, thank you for this, it's simple to use and does what it's supposed to.

However, I am running into one minor issue, I'm creating a dynamic invoice using PHP.

When I try to download it as pdf, not all the elements are in the file.

[This ](http://prntscr.com/k0xk98 )is how the invoice looks.

[This](http://prntscr.com/k0xnl7) is what I get when trying to download it.

I'm using BootStrap 3.1.0.

**Comment by kbrown01** [comment]
What structure is the top portion that is missing in?

I suspect some bootstrap col- CSS and as such it equates to floating content.

This does not always behave well.

 

You can either send us the scrape content before or create a fiddle with garbage data ….

Or I will bet the second part is in a table.

Put the first part in a table too

 

Kevin
